// ═══════════════════════════════════════════════
// ZENTRIX TECHNOLOGY — Site Configuration
// ═══════════════════════════════════════════════

export const siteConfig = {
  name: "Zentrix Technology",
  shortName: "Zentrix",
  tagline: "Where Vision Meets Velocity",
  description:
    "Zentrix Technology is a premium software engineering company from Salem, crafting enterprise software, AI solutions, automation systems, mobile applications, and digital experiences that redefine what's possible.",
  shortDescription: "Premium software engineering, AI solutions, and digital transformation.",
  url: process.env.NEXT_PUBLIC_SITE_URL || "https://zentrixtechnology.zone.id",
  domain: "zentrixtechnology.zone.id",
  permanentDomain: "zentrix.in",
  founded: 2026,
  location: {
    city: "Salem",
    state: "Tamil Nadu",
    country: "India",
    countryCode: "IN",
    coordinates: {
      lat: 11.6643,
      lng: 78.146,
    },
    address: "Salem, Tamil Nadu, India",
    timezone: "Asia/Kolkata",
  },
  contact: {
    email: "zentrixtech01@gmail.com",
    phone: "+91 88702 07425",
    whatsapp: "918870207425",
    whatsappMessage: "Hi Zentrix! I'd like to discuss a project.",
  },
  social: {
    linkedin: "https://linkedin.com/company/zentrix-technology",
    github: "https://github.com/zentrix-technology",
    instagram: "https://instagram.com/zentrix.technology",
    facebook: "https://facebook.com/zentrixtechnology",
    twitter: "https://twitter.com/zentrixtech",
  },
  stats: {
    projects: 7,
    innovationProjects: 5,
    clients: 10,
    teamSize: 5,
    yearsOfExperience: 1,
    countriesServed: 2,
    satisfaction: 100,
    uptime: 99.9,
  },
  keywords: [
    "software development company Salem",
    "web development Tamil Nadu",
    "mobile app development India",
    "enterprise software Salem",
    "AI automation solutions",
    "hospital management system",
    "school management system",
    "ERP software India",
    "digital transformation company",
    "UI UX design agency",
    "SEO marketing Salem",
    "cloud solutions India",
    "DevOps services",
    "React Next.js developers",
    "Zentrix Technology",
  ],
  services: [
    { id: "web-development", name: "Web Development", icon: "Globe" },
    { id: "app-development", name: "App Development", icon: "Smartphone" },
    { id: "enterprise-software", name: "Enterprise Software", icon: "Building2" },
    { id: "erp", name: "Custom ERP", icon: "LayoutDashboard" },
    { id: "crm", name: "CRM Development", icon: "Users" },
    { id: "hospital-management", name: "Hospital Management System", icon: "Hospital" },
    { id: "school-management", name: "School Management System", icon: "GraduationCap" },
    { id: "inventory", name: "Inventory Management", icon: "Package" },
    { id: "billing", name: "Billing Software", icon: "Receipt" },
    { id: "ai-automation", name: "AI Automation", icon: "Bot" },
    { id: "workflow-automation", name: "Workflow Automation", icon: "Workflow" },
    { id: "api-development", name: "API Development", icon: "Code2" },
    { id: "cloud-solutions", name: "Cloud Solutions", icon: "Cloud" },
    { id: "devops", name: "DevOps", icon: "Server" },
    { id: "ui-ux-design", name: "UI/UX Design", icon: "Palette" },
    { id: "seo", name: "SEO Optimization", icon: "TrendingUp" },
    { id: "meta-ads", name: "Meta Ads Management", icon: "Megaphone" },
    { id: "google-ads", name: "Google Ads", icon: "Search" },
    { id: "poster-design", name: "Poster Designing", icon: "Image" },
    { id: "video-editing", name: "Video Editing", icon: "Video" },
    { id: "brand-identity", name: "Brand Identity", icon: "Sparkles" },
    { id: "motion-graphics", name: "Motion Graphics", icon: "Film" },
  ],
  techStack: [
    { name: "Next.js", category: "Frontend", color: "#ffffff" },
    { name: "React", category: "Frontend", color: "#61DAFB" },
    { name: "TypeScript", category: "Language", color: "#3178C6" },
    { name: "Node.js", category: "Backend", color: "#339933" },
    { name: "Python", category: "AI/ML", color: "#3776AB" },
    { name: "PostgreSQL", category: "Database", color: "#4169E1" },
    { name: "MongoDB", category: "Database", color: "#47A248" },
    { name: "Redis", category: "Cache", color: "#DC382D" },
    { name: "AWS", category: "Cloud", color: "#FF9900" },
    { name: "Docker", category: "DevOps", color: "#2496ED" },
    { name: "Kubernetes", category: "DevOps", color: "#326CE5" },
    { name: "TensorFlow", category: "AI/ML", color: "#FF6F00" },
    { name: "Flutter", category: "Mobile", color: "#02569B" },
    { name: "React Native", category: "Mobile", color: "#61DAFB" },
    { name: "Prisma", category: "ORM", color: "#2D3748" },
    { name: "GraphQL", category: "API", color: "#E10098" },
    { name: "Figma", category: "Design", color: "#F24E1E" },
    { name: "Three.js", category: "3D", color: "#000000" },
  ],
  navigation: {
    main: [
      { name: "Home", href: "/" },
      { name: "Services", href: "/services" },
      { name: "Works", href: "/works" },
      { name: "Innovation Lab", href: "/innovation-lab" },
      { name: "Blog", href: "/blog" },
      { name: "About", href: "/about" },
      { name: "Contact", href: "/contact" },
    ],
    footer: {
      company: [
        { name: "About Us", href: "/about" },
        { name: "Our Team", href: "/about#team" },
        { name: "Careers", href: "/careers" },
        { name: "Innovation Lab", href: "/innovation-lab" },
        { name: "Blog", href: "/blog" },
      ],
      services: [
        { name: "Web Development", href: "/services/web-development" },
        { name: "App Development", href: "/services/app-development" },
        { name: "AI Automation", href: "/services/ai-automation" },
        { name: "Enterprise Software", href: "/services/enterprise-software" },
        { name: "UI/UX Design", href: "/services/ui-ux-design" },
      ],
      legal: [
        { name: "Privacy Policy", href: "/privacy-policy" },
        { name: "Terms of Service", href: "/terms" },
        { name: "Sitemap", href: "/sitemap" },
      ],
    },
  },
  seo: {
    defaultOgImage: "/og-image.jpg",
    twitterHandle: "@zentrixtech",
    locale: "en_IN",
  },
  analytics: {
    googleAnalyticsId: process.env.NEXT_PUBLIC_GA_ID || "",
    googleTagManagerId: process.env.NEXT_PUBLIC_GTM_ID || "",
    facebookPixelId: process.env.NEXT_PUBLIC_FB_PIXEL_ID || "",
    clarityId: process.env.NEXT_PUBLIC_CLARITY_ID || "",
    linkedinInsightTag: process.env.NEXT_PUBLIC_LINKEDIN_TAG || "",
  },
  features: {
    commandPalette: true,
    customCursor: true,
    smoothScroll: true,
    pageTransitions: true,
    backgroundMusic: true,
    accessibility: true,
    readingMode: true,
    pwa: true,
    multiLanguage: true,
    easterEgg: true, // Konami code
    floatingDock: true,
    liveCounters: true,
  },
} as const;

export type SiteConfig = typeof siteConfig;
